[build]
  # Your app lives in /frontend
  base    = "frontend"
  command = "npm run build"
  publish = "build"           # Vite configured to output build/

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
