services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_NAME
        value: test_database
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: mongodb
    databaseName: test_database
    user: backend
    region: singapore