export interface RotateItemConfig {
  code: string;
  path: string;
  itemName: string;
  display: 'yes' | 'no';
  layer: number;
  itemSize: number; // percentage from center
  rotationSpeed: number; // seconds per full rotate
  rotation: 'clockwise' | 'anti-clockwise';
  itemPositionX: number; // percentage from center
  itemPositionY: number; // percentage from center
  tiltPosition: number; // percentage
}

export const rotateConfig: RotateItemConfig[] = [
  {
    code: 'item_1',
    path: 'res/clockBG.png',
    itemName: 'clockBG',
    display: 'yes',
    layer: 1,
    itemSize: 80,
    rotationSpeed: 60,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_2',
    path: 'res/minutes_circle.png',
    itemName: 'minutes_circle',
    display: 'yes',
    layer: 2,
    itemSize: 70,
    rotationSpeed: 30,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_3',
    path: 'res/outer_circle.png',
    itemName: 'outer_circle',
    display: 'yes',
    layer: 3,
    itemSize: 90,
    rotationSpeed: 45,
    rotation: 'anti-clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_4',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 4,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_5',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 5,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_6',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 6,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_7',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 7,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_8',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 8,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_9',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 9,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_10',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 10,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_11',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 11,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_12',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 12,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_13',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 13,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_14',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 14,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_15',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 15,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_16',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 16,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_17',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 17,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_18',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 18,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_19',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 19,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
  {
    code: 'item_20',
    path: 'res/',
    itemName: '',
    display: 'no',
    layer: 20,
    itemSize: 50,
    rotationSpeed: 20,
    rotation: 'clockwise',
    itemPositionX: 0,
    itemPositionY: 0,
    tiltPosition: 0,
  },
];